export const customers = [
  {
    title: 'Atlas',
    image: 'img/customers/atlas-warren.png',
    subtitle: 'Internal System',
    description: 'In service to Warren',
    badges: ['Web Site', 'Vue JS'],
  },
  {
    title: 'Warren',
    image: 'img/customers/warren.png',
    subtitle: 'Site Warren',
    description: 'In service to Warren',
    badges: ['Web Site', 'Vue JS'],
  },
  {
    title: 'Warren',
    image: 'img/customers/warren-login.png',
    subtitle: 'Client Platform Warren',
    description: 'In service to Warren',
    badges: ['Web Site', 'Vue JS'],
  },
  {
    title: 'Petrobras',
    image: 'img/customers/seguindo-em-frente-petrobras.jpg',
    subtitle: 'Moving Forward 2017',
    description: 'In service to HUIA e H3Haus',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'NOW3',
    image: 'img/customers/now-w3haus.jpg',
    subtitle: 'Website of the Course',
    description: 'In service to HUIA and H3Haus',
    badges: ['Web Site'],
  },
  {
    title: 'Sansung',
    image: 'img/customers/sansung-nextinnovation.jpg',
    subtitle: 'Next Innovation',
    description: 'In service to HUIA and H3Haus',
    badges: ['Web Site'],
  },
  {
    title: 'Tintas Renner',
    image: 'img/customers/tintas-renner.jpg',
    subtitle: 'Site Decor',
    description: 'In service to HUIA',
    badges: ['Web Site'],
  },
  {
    title: 'Sansung',
    image: 'img/customers/sansung-galaxy-a.jpg',
    subtitle: 'Galaxy A 2017',
    description: 'In service to HUIA and H3Haus',
    badges: ['Web Site'],
  },
  {
    title: 'Cartórios de Protesto RS',
    image: 'img/customers/cartoriodeprotestors.jpg',
    subtitle: 'Site 2017',
    description: 'In service to HUIA',
    badges: ['Web Site'],
  },
  {
    title: 'SENAR',
    image: 'img/customers/senar.jpg',
    subtitle: 'Expointer 2016',
    description: 'In service to HUIA',
    badges: ['Web Site', '.NET'],
  },
  {
    title: 'Petrobras',
    image: 'img/customers/hackathon-petrobras.jpg',
    subtitle: 'Hackathon Petrobras 1° Ed',
    description: 'In service to HUIA and H3Haus',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'Tintas Renner',
    image: 'img/customers/tintas-renner-majestic.jpg',
    subtitle: 'Site Majestic',
    description: 'In service to HUIA',
    badges: ['Web Site'],
  },
  {
    title: 'ANITTA',
    image: 'img/customers/anittaagenda.jpg',
    subtitle: 'Temporary Schedule',
    description: 'In service to Base Digital',
    badges: ['Web Site'],
  },
  {
    title: 'MUSIKERIA',
    image: 'img/customers/musekeria.jpg',
    subtitle: 'Site 2016',
    description: 'In service to Base Digital',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'FAVORITA',
    image: 'img/customers/favorita_planejado_2015.jpg',
    subtitle: 'Site 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'INOVAÇÃO FIERS',
    image: 'img/customers/inovacao_2015_fiergs.jpg',
    subtitle: '2º Innovation Forum',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'TECNOPUC',
    image: 'img/customers/tecnopuc_10anos.jpg',
    subtitle: 'Digital Decade Book',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'COLCCI',
    image: 'img/customers/colcci_inverno2015.jpg',
    subtitle: 'Winter Collection 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'Forum',
    image: 'img/customers/forum-web-site.png',
    subtitle: 'Winter Collection 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'COLCCI SPFW',
    image: 'img/customers/colcci_spfw_2015.jpg',
    subtitle: 'SPFW Coverage of Colcci',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'ELEVATO',
    image: 'img/customers/elevato.jpg',
    subtitle: 'Montelupo',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'COLCCI',
    image: 'img/customers/power-skinnyjeans-edition.jpg',
    subtitle: 'Site Power Skinny Jeans',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'ARIA HT',
    image: 'img/customers/ariaht.jpg',
    subtitle: 'Site 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'DANIEL CASSIN',
    image: 'img/customers/danielCassin_natalmaisbonito2015.jpg',
    subtitle: 'Most Beautiful Christmas 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'DELL ANNO BEST',
    image: 'img/customers/dellanno_best_2015.jpg',
    subtitle: 'Campaign 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'MUDA MUNDO',
    image: 'img/customers/mudamundo.jpg',
    subtitle: 'Site 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'PEQUENOS VALENTES',
    image: 'img/customers/pequenosValentes_HMD.jpg',
    subtitle: 'HMD Project',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'DONNA WALK RUN',
    image: 'img/customers/dona_walk_run_paquetaesportes_2014.jpg',
    subtitle: 'Paqueta Esportes 2014',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'WALK RUN',
    image: 'img/customers/walkrun_paquetaesportes_2014.jpg',
    subtitle: 'Paqueta Esportes 2014',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: '#QUEROVERGOL',
    image: 'img/customers/queroVerGol_paquetaesporte.jpg',
    subtitle: 'Paquetá Sports campaign World Cup 2014',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'MEU NATAL FAVORITO',
    image: 'img/customers/natalfavorita.jpg',
    subtitle: 'Christmas Campaign',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'SOMMER',
    image: 'img/customers/sommer_sabrinasato.jpg',
    subtitle: '2015 Collection Campaign',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'NEW MÓVEIS',
    image: 'img/customers/new_moveis_sorte.jpg',
    subtitle: 'Sorte sua',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'TARTONI',
    image: 'img/customers/tartoni.jpg',
    subtitle: 'Promotional Website 2015',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'GARMIN',
    image: 'img/customers/garmin_paquetaesportes.jpg',
    subtitle: 'Site 2014',
    description: 'In service to Aldeia',
    badges: ['Web Site'],
  },
  {
    title: 'SOMMER',
    image: 'img/customers/sommer2015.jpg',
    subtitle: 'Summer 2016 Campaign',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'MINHA FAVORITA',
    image: 'img/customers/minha-favorita.jpg',
    subtitle: 'Decor website',
    description: 'In service to Aldeia',
    badges: ['Web Site', 'Word Press'],
  },
  {
    title: 'EDUCAR',
    image: 'img/customers/educarIntercampios.jpg',
    subtitle: 'School Website',
    description: 'In service to POP3',
    badges: ['Web Site'],
  },
  {
    title: 'GLAUCCIO DUTRA',
    image: 'img/customers/glaucciodutra.jpg',
    subtitle: 'Portfólio',
    description: 'In service to POP3',
    badges: ['Web Site', 'Word Press'],
  },
]
