name: Release with Custom Changelog

on:
  push:
    tags:
      - 'v*.*.*'  # Ex: v1.0.0

jobs:
  changelog:
    name: Generate Release Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Changelog and Create GitHub Release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/configs/release-changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
